using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IN8
{
    public class Disassembly
    {
        public static void DecodeInstruction(byte Instruction, out String Memonic, out int NextBytes)
        {
            Memonic = "???";
            NextBytes = 0;

            switch (Instruction)
            {
                case 0x00: Memonic = "CAL"; return;
                case 0x01: Memonic = "MTA A B"; return;
                case 0x02: Memonic = "MTA A C"; return;
                case 0x03: Memonic = "MTA A D"; return;
                case 0x04: Memonic = "MTA A E"; return;
                case 0x05: Memonic = "MTA A H"; return;
                case 0x06: Memonic = "MTA A L"; return;
                case 0x07: Memonic = "MTA A N"; NextBytes = 1; return;
                case 0x08: Memonic = "MTA B A"; return;
                case 0x09: Memonic = "RET"; return;
                case 0x0A: Memonic = "MTA B C"; return;
                case 0x0B: Memonic = "MTA B D"; return;
                case 0x0C: Memonic = "MTA B E"; return;
                case 0x0D: Memonic = "MTA B H"; return;
                case 0x0E: Memonic = "MTA B L"; return;
                case 0x0F: Memonic = "MTA B N"; NextBytes = 1; return;
                case 0x10: Memonic = "SSL"; return;
                case 0x11: Memonic = "NPB"; return;
                case 0x12: Memonic = "MFA A C"; return;
                case 0x13: Memonic = "MFA A D"; return;
                case 0x14: Memonic = "MFA A E"; return;
                case 0x15: Memonic = "MFA A H"; return;
                case 0x16: Memonic = "MFA A L"; return;
                case 0x17: Memonic = "NOT A"; return;
                case 0x18: Memonic = "NPC"; return;
                case 0x19: Memonic = "SSR"; return;
                case 0x1A: Memonic = "MFA B C"; return;
                case 0x1B: Memonic = "MFA B D"; return;
                case 0x1C: Memonic = "MFA B E"; return;
                case 0x1D: Memonic = "MFA B H"; return;
                case 0x1E: Memonic = "MFA B L"; return;
                case 0x1F: Memonic = "NOT B"; return;
                case 0x20: Memonic = "ADD A A"; return;
                case 0x21: Memonic = "ADD A B"; return;
                case 0x22: Memonic = "ADD A C"; return;
                case 0x23: Memonic = "ADD A D"; return;
                case 0x24: Memonic = "ADD A E"; return;
                case 0x25: Memonic = "ADD A H"; return;
                case 0x26: Memonic = "ADD A L"; return;
                case 0x27: Memonic = "ADD A N"; NextBytes = 1; return;
                case 0x28: Memonic = "ADD B A"; return;
                case 0x29: Memonic = "ADD B B"; return;
                case 0x2A: Memonic = "ADD B C"; return;
                case 0x2B: Memonic = "ADD B D"; return;
                case 0x2C: Memonic = "ADD B E"; return;
                case 0x2D: Memonic = "ADD B H"; return;
                case 0x2E: Memonic = "ADD B L"; return;
                case 0x2F: Memonic = "ADD B N"; NextBytes = 1; return;
                case 0x30: Memonic = "SUB A A"; return;
                case 0x31: Memonic = "SUB A B"; return;
                case 0x32: Memonic = "SUB A C"; return;
                case 0x33: Memonic = "SUB A D"; return;
                case 0x34: Memonic = "SUB A E"; return;
                case 0x35: Memonic = "SUB A H"; return;
                case 0x36: Memonic = "SUB A L"; return;
                case 0x37: Memonic = "SUB A N"; NextBytes = 1; return;
                case 0x38: Memonic = "SUB B A"; return;
                case 0x39: Memonic = "SUB B B"; return;
                case 0x3A: Memonic = "SUB B C"; return;
                case 0x3B: Memonic = "SUB B D"; return;
                case 0x3C: Memonic = "SUB B E"; return;
                case 0x3D: Memonic = "SUB B H"; return;
                case 0x3E: Memonic = "SUB B L"; return;
                case 0x3F: Memonic = "SUB B N"; NextBytes = 1; return;
                case 0x40: Memonic = "MUL A A"; return;
                case 0x41: Memonic = "MUL A B"; return;
                case 0x42: Memonic = "MUL A C"; return;
                case 0x43: Memonic = "MUL A D"; return;
                case 0x44: Memonic = "MUL A E"; return;
                case 0x45: Memonic = "MUL A H"; return;
                case 0x46: Memonic = "MUL A L"; return;
                case 0x47: Memonic = "MUL A N"; NextBytes = 1; return;
                case 0x48: Memonic = "MUL B A"; return;
                case 0x49: Memonic = "MUL B B"; return;
                case 0x4A: Memonic = "MUL B C"; return;
                case 0x4B: Memonic = "MUL B D"; return;
                case 0x4C: Memonic = "MUL B E"; return;
                case 0x4D: Memonic = "MUL B H"; return;
                case 0x4E: Memonic = "MUL B L"; return;
                case 0x4F: Memonic = "MUL B N"; NextBytes = 1; return;
                case 0x50: Memonic = "DIV A A"; return;
                case 0x51: Memonic = "DIV A B"; return;
                case 0x52: Memonic = "DIV A C"; return;
                case 0x53: Memonic = "DIV A D"; return;
                case 0x54: Memonic = "DIV A E"; return;
                case 0x55: Memonic = "DIV A H"; return;
                case 0x56: Memonic = "DIV A L"; return;
                case 0x57: Memonic = "DIV A N"; NextBytes = 1; return;
                case 0x58: Memonic = "DIV B A"; return;
                case 0x59: Memonic = "DIV B B"; return;
                case 0x5A: Memonic = "DIV B C"; return;
                case 0x5B: Memonic = "DIV B D"; return;
                case 0x5C: Memonic = "DIV B E"; return;
                case 0x5D: Memonic = "DIV B H"; return;
                case 0x5E: Memonic = "DIV B L"; return;
                case 0x5F: Memonic = "DIV B N"; NextBytes = 1; return;
                case 0x60: Memonic = "MOD A A"; return;
                case 0x61: Memonic = "MOD A B"; return;
                case 0x62: Memonic = "MOD A C"; return;
                case 0x63: Memonic = "MOD A D"; return;
                case 0x64: Memonic = "MOD A E"; return;
                case 0x65: Memonic = "MOD A H"; return;
                case 0x66: Memonic = "MOD A L"; return;
                case 0x67: Memonic = "MOD A N"; NextBytes = 1; return;
                case 0x68: Memonic = "MOD B A"; return;
                case 0x69: Memonic = "MOD B B"; return;
                case 0x6A: Memonic = "MOD B C"; return;
                case 0x6B: Memonic = "MOD B D"; return;
                case 0x6C: Memonic = "MOD B E"; return;
                case 0x6D: Memonic = "MOD B H"; return;
                case 0x6E: Memonic = "MOD B L"; return;
                case 0x6F: Memonic = "MOD B N"; NextBytes = 1; return;
                case 0x70: Memonic = "OVA"; return;
                case 0x71: Memonic = "AND A B"; return;
                case 0x72: Memonic = "AND A C"; return;
                case 0x73: Memonic = "AND A D"; return;
                case 0x74: Memonic = "AND A E"; return;
                case 0x75: Memonic = "AND A H"; return;
                case 0x76: Memonic = "AND A L"; return;
                case 0x77: Memonic = "AND A N"; NextBytes = 1; return;
                case 0x78: Memonic = "AND B A"; return;
                case 0x79: Memonic = "OVB"; return;
                case 0x7A: Memonic = "AND B C"; return;
                case 0x7B: Memonic = "AND B D"; return;
                case 0x7C: Memonic = "AND B E"; return;
                case 0x7D: Memonic = "AND B H"; return;
                case 0x7E: Memonic = "AND B L"; return;
                case 0x7F: Memonic = "AND B N"; NextBytes = 1; return;
                case 0x80: Memonic = "MUS"; return;
                case 0x81: Memonic = "BOR A B"; return;
                case 0x82: Memonic = "BOR A C"; return;
                case 0x83: Memonic = "BOR A D"; return;
                case 0x84: Memonic = "BOR A E"; return;
                case 0x85: Memonic = "BOR A H"; return;
                case 0x86: Memonic = "BOR A L"; return;
                case 0x87: Memonic = "BOR A N"; NextBytes = 1; return;
                case 0x88: Memonic = "BOR B A"; return;
                case 0x89: Memonic = "DIS"; return;
                case 0x8A: Memonic = "BOR B C"; return;
                case 0x8B: Memonic = "BOR B D"; return;
                case 0x8C: Memonic = "BOR B E"; return;
                case 0x8D: Memonic = "BOR B H"; return;
                case 0x8E: Memonic = "BOR B L"; return;
                case 0x8F: Memonic = "BOR B N"; NextBytes = 1; return;
                case 0x90: Memonic = "XOR A A"; return;
                case 0x91: Memonic = "XOR A B"; return;
                case 0x92: Memonic = "XOR A C"; return;
                case 0x93: Memonic = "XOR A D"; return;
                case 0x94: Memonic = "XOR A E"; return;
                case 0x95: Memonic = "XOR A H"; return;
                case 0x96: Memonic = "XOR A L"; return;
                case 0x97: Memonic = "XOR A N"; NextBytes = 1; return;
                case 0x98: Memonic = "XOR B A"; return;
                case 0x99: Memonic = "XOR B B"; return;
                case 0x9A: Memonic = "XOR B C"; return;
                case 0x9B: Memonic = "XOR B D"; return;
                case 0x9C: Memonic = "XOR B E"; return;
                case 0x9D: Memonic = "XOR B H"; return;
                case 0x9E: Memonic = "XOR B L"; return;
                case 0x9F: Memonic = "XOR B N"; NextBytes = 1; return;
                case 0xA0: Memonic = "PSH A"; return;
                case 0xA1: Memonic = "PSH B"; return;
                case 0xA2: Memonic = "PSH C"; return;
                case 0xA3: Memonic = "PSH D"; return;
                case 0xA4: Memonic = "PSH E"; return;
                case 0xA5: Memonic = "PSH H"; return;
                case 0xA6: Memonic = "PSH L"; return;
                case 0xA7: Memonic = "PSH N"; NextBytes = 1; return;
                case 0xA8: Memonic = "POP A"; return;
                case 0xA9: Memonic = "POP B"; return;
                case 0xAA: Memonic = "POP C"; return;
                case 0xAB: Memonic = "POP D"; return;
                case 0xAC: Memonic = "POP E"; return;
                case 0xAD: Memonic = "POP H"; return;
                case 0xAE: Memonic = "POP L"; return;
                case 0xAF: Memonic = "RSP"; return;
                case 0xB0: Memonic = "PEK A"; return;
                case 0xB1: Memonic = "PEK B"; return;
                case 0xB2: Memonic = "PEK C"; return;
                case 0xB3: Memonic = "PEK D"; return;
                case 0xB4: Memonic = "PEK E"; return;
                case 0xB5: Memonic = "PEK H"; return;
                case 0xB6: Memonic = "PEK L"; return;
                case 0xB7: Memonic = "SSP"; return;
                case 0xB8: Memonic = "LOD A"; return;
                case 0xB9: Memonic = "LOD B"; return;
                case 0xBA: Memonic = "LOD C"; return;
                case 0xBB: Memonic = "LOD D"; return;
                case 0xBC: Memonic = "LOD E"; return;
                case 0xBD: Memonic = "LOD H"; return;
                case 0xBE: Memonic = "LOD L"; return;
                case 0xBF: Memonic = "LLT"; NextBytes = 2; return;
                case 0xC0: Memonic = "STR A"; return;
                case 0xC1: Memonic = "STR B"; return;
                case 0xC2: Memonic = "STR C"; return;
                case 0xC3: Memonic = "STR D"; return;
                case 0xC4: Memonic = "STR E"; return;
                case 0xC5: Memonic = "STR H"; return;
                case 0xC6: Memonic = "STR L"; return;
                case 0xC7: Memonic = "STR N"; NextBytes = 1; return;
                case 0xC8: Memonic = "LDW"; return;
                case 0xC9: Memonic = "SDW"; return;
                case 0xCA: Memonic = "STP"; return;
                case 0xCB: Memonic = "CFP"; return;
                case 0xCC: Memonic = "SWP"; return;
                case 0xCD: Memonic = "RIP"; return;
                case 0xCE: Memonic = "JMP"; return;
                case 0xCF: Memonic = "JPL"; NextBytes = 2; return;
                case 0xD0: Memonic = "BIE"; return;
                case 0xD1: Memonic = "BNE"; return;
                case 0xD2: Memonic = "BGT"; return;
                case 0xD3: Memonic = "BLT"; return;
                case 0xD4: Memonic = "BEG"; return;
                case 0xD5: Memonic = "BEL"; return;
                case 0xD6: Memonic = "BSL"; return;
                case 0xD7: Memonic = "BSG"; return;
                case 0xD8: Memonic = "CAD A"; return;
                case 0xD9: Memonic = "CAD B"; return;
                case 0xDA: Memonic = "CAD C"; return;
                case 0xDB: Memonic = "CAD D"; return;
                case 0xDC: Memonic = "CAD E"; return;
                case 0xDD: Memonic = "CAD H"; return;
                case 0xDE: Memonic = "CAD L"; return;
                case 0xDF: Memonic = "CAD N"; NextBytes = 1; return;
                case 0xE0: Memonic = "CSB A"; return;
                case 0xE1: Memonic = "CSB B"; return;
                case 0xE2: Memonic = "CSB C"; return;
                case 0xE3: Memonic = "CSB D"; return;
                case 0xE4: Memonic = "CSB E"; return;
                case 0xE5: Memonic = "CSB H"; return;
                case 0xE6: Memonic = "CSB L"; return;
                case 0xE7: Memonic = "CSB N"; NextBytes = 1; return;
                case 0xE8: Memonic = "ADS A"; return;
                case 0xE9: Memonic = "ADS B"; return;
                case 0xEA: Memonic = "ADS C"; return;
                case 0xEB: Memonic = "ADS D"; return;
                case 0xEC: Memonic = "ADS E"; return;
                case 0xED: Memonic = "ADS H"; return;
                case 0xEE: Memonic = "ADS L"; return;
                case 0xEF: Memonic = "ADS N"; NextBytes = 1; return;
                case 0xF0: Memonic = "SBS A"; return;
                case 0xF1: Memonic = "SBS B"; return;
                case 0xF2: Memonic = "SBS C"; return;
                case 0xF3: Memonic = "SBS D"; return;
                case 0xF4: Memonic = "SBS E"; return;
                case 0xF5: Memonic = "SBS H"; return;
                case 0XF6: Memonic = "SBS L"; return;
                case 0xF7: Memonic = "SBS N"; NextBytes = 1; return;
                case 0xF8: Memonic = "OUT"; return;
                case 0xF9: Memonic = "IIN"; return;
                case 0xFA: Memonic = "NPE"; return;
                case 0xFB: Memonic = "JIG"; NextBytes = 2; return;
                case 0xFC: Memonic = "NPG"; return;
                case 0xFD: Memonic = "CLK"; return;
                case 0xFE: Memonic = "SFJ"; return;
                case 0xFF: Memonic = "SBJ"; return;
            }
        }
    }
}
